CREATE TABLE TB_NOTAFISCAL(ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,ID_NF INT NOT NULL, ID_ITEM INT NOT NULL, COD_PROD INT NOT NULL, VALOR_UNIT DECIMAL NOT NULL, QUANTIDADE INT NOT NULL, DESCONTO INT);

INSERT INTO tb_notafiscal(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO)
 values(1,1,1,25,10,5);

INSERT INTO tb_notafiscal(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO)
 values(1,2,2,14,3,null);

INSERT INTO tb_notafiscal(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO)
 values(1,3,3,15,2,null);

INSERT INTO tb_notafiscal(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO)
 values(1,4,4,10,1,null);

INSERT INTO tb_notafiscal(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO)
 values(1,5,5,30,1,null);

INSERT INTO tb_notafiscal(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO)
 values(4,1,5,30,10,15);

INSERT INTO tb_notafiscal(ID_NF,ID_ITEM,COD_PROD,VALOR_UNIT,QUANTIDADE,DESCONTO)
 values(4,3,1,25,13,5);